/* Action type constants — mirrors webapp/src/redux/types/index.ts.
 *
 * Kept verbatim so handler/dispatch sites can be copy/pasted from the
 * webapp with no renames. The actual reducer in src/redux/reducers/index.ts
 * only implements the subset used by the auth + tabs UI today; the rest
 * are placeholders for the realtime/calls/map ports. */

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ALERTS = "SET_ALERTS";
export const SET_MUTATE_ALERTS = "SET_MUTATE_ALERTS";
export const SET_FILTERED_ALERTS = "SET_FILTERED_ALERTS";
export const SET_CLEAR_ALERTS = "SET_CLEAR_ALERTS";

export const SET_PENDING_CALL_ALERTS = "SET_PENDING_CALL_ALERTS";
export const REMOVE_PENDING_CALL_ALERTS = "REMOVE_PENDING_CALL_ALERTS";
export const CLEAR_PENDING_CALL_ALERTS = "CLEAR_PENDING_CALL_ALERTS";

export const SET_CONTACTS_LIST = "SET_CONTACTS_LIST";
export const SET_CONTACTS_LIST_OVERRIDE = "SET_CONTACTS_LIST_OVERRIDE";

export const SET_NOTIFICATIONS_LIST = "SET_NOTIFICATIONS_LIST";
export const SET_NOTIFICATIONS_LIST_OVERRIDE = "SET_NOTIFICATIONS_LIST_OVERRIDE";
export const SET_NOTIFICATIONS_LIST_APPEND = "SET_NOTIFICATIONS_LIST_APPEND";

export const SET_MESSAGES_LIST = "SET_MESSAGES_LIST";
export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";
export const SET_MESSAGES_LIST_OVERRIDE = "SET_MESSAGES_LIST_OVERRIDE";

export const SET_TOGGLE_RIGHT_WIDGET = "SET_TOGGLE_RIGHT_WIDGET";
export const SET_CONVERSATION_SETUP = "SET_CONVERSATION_SETUP";

export const SET_SCREEN_SIZE_LISTENER = "SET_SCREEN_SIZE_LISTENER";
export const SET_PATHNAME_LISTENER = "SET_PATHNAME_LISTENER";

export const SET_PENDING_MESSAGES_LIST = "SET_PENDING_MESSAGES_LIST";
export const SET_APPROVED_PENDING_MESSAGES_LIST =
  "SET_APPROVED_PENDING_MESSAGES_LIST";
export const SET_IS_TYPING_LIST = "SET_IS_TYPING_LIST";
export const SET_REMOVE_IS_TYPING_LIST = "SET_REMOVE_IS_TYPING_LIST";

export const SET_CALLS_LIST = "SET_CALLS_LIST";
export const END_CALL_LIST = "END_CALL_LIST";
export const SET_REJECTED_CALL_LIST = "SET_REJECTED_CALL_LIST";
export const REMOVE_REJECTED_CALL_LIST = "REMOVE_REJECTED_CALL_LIST";
export const CHECK_AND_ADD_NEW_CALL_LIST_WINDOW =
  "CHECK_AND_ADD_NEW_CALL_LIST_WINDOW";
export const MEDIA_TRACK_HOLDER = "MEDIA_TRACK_HOLDER";
export const MEDIA_MY_VIDEO_HOLDER = "MEDIA_MY_VIDEO_HOLDER";

export const SET_ACTIVE_USERS_LIST = "SET_ACTIVE_USERS_LIST";
export const UPDATE_ACTIVE_USERS_LIST = "UPDATE_ACTIVE_USERS_LIST";

export const SET_POSTS_FEED_LIST = "SET_POSTS_FEED_LIST";
export const SET_MUTATE_POSTS_FEED_LIST = "SET_MUTATE_POSTS_FEED_LIST";

export const SET_EMOJIS_LIST = "SET_EMOJIS_LIST";
export const SET_MINIMIZED_CONVERSATION = "SET_MINIMIZED_CONVERSATION";
export const CLOSE_MINIMIZED_CONVERSATION = "CLOSE_MINIMIZED_CONVERSATION";
export const SET_MINIMIZED_CONVERSATION_OVERRIDE =
  "SET_MINIMIZED_CONVERSATION_OVERRIDE";

export const SET_PAGE_MODAL = "SET_PAGE_MODAL";
export const SET_USER_SETTINGS = "SET_USER_SETTINGS";
export const SET_COORDINATES = "SET_COORDINATES";
export const SET_RAW_COORDINATES = "SET_RAW_COORDINATES";

export const SET_PREVIEW_PARTICIPANTS = "SET_PREVIEW_PARTICIPANTS";
export const SET_PREVIEW_PARTICIPANTS_BULK = "SET_PREVIEW_PARTICIPANTS_BULK";
export const REMOVE_PREVIEW_PARTICIPANT = "REMOVE_PREVIEW_PARTICIPANT";
